export const SKILLS = {
  HARD_SKILLS: {
    MARKUP: "skills.hardSkills.markupLanguages",
    HTML: "HTML",
    XML: "XML",
    STYLESHEET: "skills.hardSkills.stylesheetLanguages",
    CSS: "CSS",
    SASS: "SASS",
    PROGRAMMING: "skills.hardSkills.programmingLanguages",
    JAVASCRIPT: "JavaScript",
    TYPESCRIPT: "TypeScript",
    JAVA: "Java",
    FRONTEND_LIBRARIES: "skills.hardSkills.frontendLibraries",
    REACT: "React",
    ANGULAR: "Angular",
    FRAMEWORKS_ENVIRONMENTS: "skills.hardSkills.frameworksEnvironments",
    NODE_JS: "Node.js",
    EXPRESS: "Express",
    DATABASES: "skills.hardSkills.databases",
    POSTGRESQL: "PostgreSQL",
    MONGODB: "MongoDB",
    VERSION_CONTROL: "skills.hardSkills.versionControl",
    GIT: "Git",
    GITHUB: "GitHub",
    OTHER_TOOLS: "skills.hardSkills.otherTools",
    THREE_JS: "Three.js",
    JIRA: "Jira"
  },
  SOFT_SKILLS: {
    PROBLEM_SOLVING: "skills.softSkills.problemSolving",
    PROBLEM_SOLVING_SVG: "problem-solving",
    SELF_MANAGEMENT: "skills.softSkills.selfManagement",
    SELF_MANAGEMENT_SVG: "self-management",
    ABILITY_TO_TEACH: "skills.softSkills.abilityToTeach",
    ABILITY_TO_TEACH_SVG: "ability-to-teach",
    TEAMWORK: "skills.softSkills.teamwork",
    TEAMWORK_SVG: "teamwork",
    ADAPTABILITY: "skills.softSkills.adaptability",
    ADAPTABILITY_SVG: "adaptability"
  }
};
